### ISSUE TITLE
fix: Display business reviews

### ISSUE THREAD

**Issue by marutim** [WordImpress/Yelp-Widget-Premium#36]
## Overview
Business reviews are not working.

If the option is checked in the widget, it shows nothing and if you have WP_DEBUG enabled, you can see a notice and a warning.
`Notice: Undefined property: stdClass::$reviews in /app/public/wp-content/plugins/Yelp-Widget-Premium-master/includes/template-parts/business.php on line 44 Warning: Invalid argument supplied for foreach() in /app/public/wp-content/plugins/Yelp-Widget-Premium-master/includes/template-parts/business.php on line 44`

## Screenshots
![1](https://user-images.githubusercontent.com/3498917/36497726-2474b6d4-1762-11e8-8d28-0256bcc129d0.png)
![2](https://user-images.githubusercontent.com/3498917/36497728-25b67f78-1762-11e8-9dce-4df911ee7a61.png)

**Comment by DevinWalker** [comment]
This notice was only displaying with businesses not returning any reviews from Yelp's API. It's strange because some businesses have reviews but don't return any. I'm assuming the API only returns reviews that are timely and relevant. The business above only has a small number of reviews that are old. 

I'm releasing 2.0.1 with the fix for above and another unrelated fix. Closing this one out as this was resolved here:  a21bbf415292fac71655bedeaf01b48b65c5b14a
